# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=kisuvilu
export POSTGRES_PASSWORD=Dmk.0704970993
export POSTGRES_HOST=kisuvilu.c2tvljks947h.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=my-2022-dev
export AWS_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=testing
export URL=http://localhost:8100
export AWS_ACCESS_KEY_ID=ASIA5WKXC5RVJRT54A46
export AWS_SECRET_ACCESS_KEY=ia+lTPuQSwL3G5A3bKCBWBZcQKM2jTZxDMTUx8Cv
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEHQaDGqWXrTMgIOiPBz2SyLVAaTs1w+EzpCQZ010Jh1ckh62IlCgBCosnzPuBfrssEtmEXYiP3oZpcLSo/UTbYbmw/Hv1B0n24gQYBbrgZBZ8UojGJuDa74d7dalnOVQ0kts4DQxcNWeXLEtrPbqA2QW6u2sAhYMHZCxUikUzZPQiu9xPZGDVZTe+UgQgCCzYUDFIwsFYTVkCYLQLxoPcowcweZeT8lZTXyZ4bN7kCHLYIiRuOeG6Me1thpHnOklMXdei70xZ9naTjkiaOLbN2KBQMMAW0oPhOIt/C97kjP+5ho6n/OWbyjf6vWaBjItzSEolxVyNDCI0+mOdcTBO0h07+oRmagfnDnuCCtP2D4cqLJykIbkDMYrD4SJ

