# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=uda
export POSTGRES_PASSWORD=Denmk2021
export POSTGRES_HOST=uda.ccalsoledtyf.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=myawsbucket2040
export AWS_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=testing
export URL=http://localhost:8100
export AWS_ACCESS_KEY_ID=ASIA5RLJ6YN4LNMXNEWT
export AWS_SECRET_ACCESS_KEY=gVdMHvDYjFnx2N0NuX2246SMHS2CphYJtkishIdk
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEBgaDO7lbFWFLx9uaSJwOyLVAQMhzIrdg3wX28hPFanjlALjlPBVeVUTOI4oX5nS6w1UiIwHFQ/GOQmPOxEtNivql3DxlzZC7yRtEPdB/uQnFQcsN6LzeAQdqPKPe4aymM7PaMCZcxGHHgSpHG7mttupjKunEUFeQ1KCFRo4CEED6akER8mPRxfB/xd29nDbCMPusZga8y62Ui7BVFe2he61GO6yLudX8YEivshrwam8AL0acG8w3Csg4Li2+jdlkrELETxHQvbGVKGRalKmC9NO8SgQoeuPjNJcUDYjQQeCGNiTmaiJhyio6ZmbBjIt9V6uXHS6ubrkICBF+vhSs+CNkMT1N56YrxDDM0oZgM4Uo+XgmDRClx0AJgn1