name: Node.js CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -uses: actions/checkout@v3
      -run: docker-compose -f docker-compose-build.yaml build --parallel
      -run: docker tag udagram-frontend:local kisuvilu/tag udagram-frontend:local:v1
      -run: docker tag udagram-api-user kisuvilu/tag udagram-api-user:v1 
      -run: docker tag udagram--api-feed kisuvilu/tag udagram-api-feed:v1
      -run: docker tag reverseproxy  kisuvilu/tag reverseproxy:v1
      -run: push docker kisuvilu/tag udagram-frontend:local:v1
      -run: push docker kisuvilu/tag udagram-api-user:v1 
      -run: push docker kisuvilu/tag udagram-api-feed:v1 
      -run: push docker kisuvilu/tag reverseproxy:v1


      


